import { FormEvent, useMemo, useState } from "react";
import { ArrowLeft, ArrowUpRight, Check, Mail, MapPin, Phone, X } from "lucide-react";
import { useLocation } from "wouter";
import { Breadcrumb, PageShell, SectionLabel } from "@/components/layout/SiteChrome";
import { contactChannels, formOptions, sectionEyebrows } from "@/data/products";
import { useI18n } from "@/i18n";

type FormState = { enquiry: string; leatherType: string; thickness: string; name: string; company: string; email: string; country: string; phone: string; application: string; volume: string; message: string };
const initialForm: FormState = { enquiry: "", leatherType: "", thickness: "", name: "", company: "", email: "", country: "", phone: "", application: "", volume: "", message: "" };

export default function Contact() {
  const [location] = useLocation();
  const { t } = useI18n();
  const params = new URLSearchParams(location.split("?")[1] || "");
  const [step, setStep] = useState(1);
  const [reviewOpen, setReviewOpen] = useState(false);
  const [submitted, setSubmitted] = useState(false);
  const [form, setForm] = useState<FormState>({ ...initialForm, enquiry: params.get("enquiry") || "" });
  const update = (key: keyof FormState, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const leatherOptions = useMemo(() => [{ value: "Full grain", label: t.leatherFullGrain }, { value: "Top grain", label: t.leatherTopGrain }, { value: "Suede", label: t.leatherSuede }, { value: "Split leather", label: t.leatherSplit }], [t]);
  const thicknessOptions = ["0.7–0.9 mm", "0.9–1.1 mm", "1.1–1.3 mm", "1.2–1.4 mm", "Custom / please advise"];
  const canContinue = step === 1 ? Boolean(form.enquiry) : Boolean(form.leatherType && form.thickness);
  const message = ["Anatolia Hides — B2B material enquiry", `Request: ${form.enquiry}`, `Company: ${form.company}`, `Target delivery country: ${form.country}`, `Leather type: ${form.leatherType}`, `Thickness: ${form.thickness}`, `Contact name: ${form.name}`, `Email: ${form.email}`, `Phone / WhatsApp: ${form.phone || "—"}`, `Application: ${form.application || "—"}`, `Programme size: ${form.volume || "—"}`, `Brief: ${form.message || "—"}`].join("\n");
  const whatsappUrl = `https://wa.me/905368476521?text=${encodeURIComponent(message)}`;
  const handleSubmit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setReviewOpen(true); };
  const confirmWhatsApp = () => { setReviewOpen(false); setSubmitted(true); window.setTimeout(() => window.location.assign(whatsappUrl), 1500); };
  const resetForm = () => { setSubmitted(false); setStep(1); setForm({ ...initialForm, enquiry: "" }); };

  return <PageShell><main>
    <section className="bg-[#e8dfd3] px-5 pb-20 pt-36 md:px-10 md:pb-28 md:pt-48 lg:px-14"><div className="mx-auto max-w-[1440px]"><Breadcrumb current={t.navContact} /><div className="mt-12 grid gap-10 lg:grid-cols-[0.42fr_1fr] lg:gap-24"><div><SectionLabel number="01">{sectionEyebrows.reach}</SectionLabel><p className="mt-8 max-w-[230px] font-sans text-xs leading-6 text-[#77695c]">{t.contactIntro}</p></div><div><h1 className="max-w-[920px] font-serif text-6xl leading-[0.88] tracking-[-0.065em] md:text-8xl">{t.contactTitle.split(" ").slice(0, 3).join(" ")}<br /><em className="font-light text-[#a27655]">{t.contactTitle.split(" ").slice(3).join(" ")}</em></h1><p className="mt-8 max-w-[650px] font-sans text-base leading-8 text-[#655b52]">{t.contactIntro}</p></div></div></div></section>
    <section className="bg-[#f3efe8] px-5 py-24 md:px-10 md:py-32 lg:px-14"><div className="mx-auto grid max-w-[1440px] gap-16 lg:grid-cols-[0.6fr_1fr] lg:gap-24">
      <div><SectionLabel number="02">{t.directEnquiry}</SectionLabel><h2 className="mt-7 max-w-[440px] font-serif text-5xl leading-[0.95] tracking-[-0.05em] md:text-6xl">{t.contactTitle}</h2><p className="mt-7 max-w-[390px] font-sans text-sm leading-7 text-[#655b52]">{t.formSubtitle}</p><div className="mt-12 space-y-7">{contactChannels.map((channel) => <div key={channel.label} className="flex gap-4 border-t border-[#1b1916]/15 pt-5"><div className="grid size-9 shrink-0 place-items-center rounded-full border border-[#a48566]/50 text-[#9b795b]"><Phone size={14} strokeWidth={1.5} /></div><div><p className="font-sans text-[10px] font-semibold uppercase tracking-[0.18em] text-[#9b795b]">{channel.label}</p><a href={channel.href} className="mt-1 block font-serif text-2xl tracking-[-0.03em] transition-colors hover:text-[#9b795b]">{channel.value}</a><p className="mt-1 font-sans text-xs text-[#77695c]">{channel.note}</p></div></div>)}</div><div className="mt-10 flex flex-wrap gap-4 font-sans text-xs text-[#77695c]"><span className="inline-flex items-center gap-2"><MapPin size={14} />Zeytinburnu, Istanbul</span><span className="inline-flex items-center gap-2"><MapPin size={14} />Switzerland</span></div></div>
      <div id="contact-form" className="bg-[#e8dfd3] p-6 md:p-10"><div className="flex items-start justify-between gap-4"><div><p className="font-sans text-[10px] font-semibold uppercase tracking-[0.22em] text-[#9b795b]">{t.materialLibrary}</p><h2 className="mt-3 font-serif text-4xl tracking-[-0.04em]">{t.formTitle}</h2></div><Mail size={22} strokeWidth={1.3} className="mt-2 text-[#9b795b]" /></div>
        {submitted ? <div className="luxury-confirmation mt-10 border border-[#9b795b]/35 bg-[#f3efe8] p-8"><div className="confirmation-seal"><Check size={21} /></div><h3 className="mt-6 font-serif text-3xl">{t.submitted}</h3><p className="mt-3 max-w-[390px] font-sans text-sm leading-6 text-[#655b52]">{t.submittedCopy}</p><div className="mt-8 flex items-center gap-3 font-sans text-[10px] font-semibold uppercase tracking-[0.16em] text-[#9b795b]"><span className="confirmation-dot" />{t.openWhatsApp} <span className="confirmation-line" /></div><p className="mt-5 font-sans text-[10px] uppercase tracking-[0.14em] text-[#9b795b]">Opening secure conversation…</p><button type="button" onClick={resetForm} className="mt-7 border-b border-[#1b1916]/20 pb-2 font-sans text-[10px] font-semibold uppercase tracking-[0.17em] text-[#815d42]">{t.startAgain}</button></div> : <form onSubmit={handleSubmit} className="mt-9">
          <div className="mb-10 flex items-center gap-2">{[t.stepBrief, t.stepMaterial, t.stepContact].map((label, index) => <div key={label} className="flex flex-1 items-center gap-2"><span className={`grid size-7 place-items-center rounded-full font-sans text-[10px] font-semibold ${step >= index + 1 ? "bg-[#211a15] text-[#f3efe8]" : "border border-[#1b1916]/20 text-[#77695c]"}`}>0{index + 1}</span><span className={`hidden font-sans text-[10px] uppercase tracking-[0.13em] sm:inline ${step >= index + 1 ? "text-[#1b1916]" : "text-[#77695c]"}`}>{label}</span>{index < 2 && <span className="h-px flex-1 bg-[#1b1916]/15" />}</div>)}</div>
          {step === 1 && <div className="space-y-7"><div><p className="field-label">{t.stepOneTitle}</p><p className="mt-2 font-sans text-sm leading-6 text-[#77695c]">{t.stepOneCopy}</p></div><div className="grid gap-3 sm:grid-cols-2">{[{ value: t.sample, label: t.sample }, { value: t.quote, label: t.quote }, { value: t.technical, label: t.technical }, { value: t.partnership, label: t.partnership }].map((option) => <button type="button" key={option.value} onClick={() => update("enquiry", option.value)} className={`border p-4 text-left font-serif text-xl tracking-[-0.03em] transition-colors ${form.enquiry === option.value ? "border-[#9b795b] bg-[#f3efe8]" : "border-[#1b1916]/15 hover:border-[#9b795b]/70"}`}>{option.label}</button>)}</div></div>}
          {step === 2 && <div className="space-y-7"><div><p className="field-label">{t.stepTwoTitle}</p><p className="mt-2 font-sans text-sm leading-6 text-[#77695c]">{t.stepTwoCopy}</p></div><label className="field-label">{t.leatherType}<select required value={form.leatherType} onChange={(event) => update("leatherType", event.target.value)} className="field-input"><option value="">{t.select}</option>{leatherOptions.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label><label className="field-label">{t.thickness}<select required value={form.thickness} onChange={(event) => update("thickness", event.target.value)} className="field-input"><option value="">{t.select}</option>{thicknessOptions.map((option) => <option key={option}>{option}</option>)}</select></label></div>}
          {step === 3 && <div className="space-y-6"><div><p className="field-label">{t.stepThreeTitle}</p><p className="mt-2 font-sans text-sm leading-6 text-[#77695c]">{t.stepThreeCopy}</p></div><div className="grid gap-6 md:grid-cols-2"><label className="field-label">{t.fullName}<input required value={form.name} onChange={(event) => update("name", event.target.value)} placeholder="Your name" className="field-input" /></label><label className="field-label">{t.company}<input required value={form.company} onChange={(event) => update("company", event.target.value)} placeholder="Company name" className="field-input" /></label></div><div className="grid gap-6 md:grid-cols-2"><label className="field-label">{t.email}<input required type="email" value={form.email} onChange={(event) => update("email", event.target.value)} placeholder="name@company.com" className="field-input" /></label><label className="field-label">{t.phone}<input value={form.phone} onChange={(event) => update("phone", event.target.value)} placeholder="+00" className="field-input" /></label></div><div className="grid gap-6 md:grid-cols-2"><label className="field-label">{t.country}<input required value={form.country} onChange={(event) => update("country", event.target.value)} placeholder="Italy, Germany, UK…" className="field-input" /></label><label className="field-label">{t.application}<select value={form.application} onChange={(event) => update("application", event.target.value)} className="field-input"><option value="">{t.select}</option>{formOptions.application.map((option) => <option key={option}>{option}</option>)}</select></label></div><label className="field-label">{t.message}<textarea value={form.message} onChange={(event) => update("message", event.target.value)} rows={3} placeholder="Material, finish, colour, timeline…" className="field-input resize-none" /></label></div>}
          <div className="mt-9 flex flex-wrap items-center gap-4">{step > 1 && <button type="button" onClick={() => setStep((current) => current - 1)} className="inline-flex items-center gap-2 border-b border-[#1b1916]/25 pb-2 font-sans text-[10px] font-semibold uppercase tracking-[0.17em]"><ArrowLeft size={14} />{t.back}</button>}{step < 3 ? <button type="button" disabled={!canContinue} onClick={() => setStep((current) => current + 1)} className="group inline-flex items-center gap-3 rounded-full bg-[#211a15] px-5 py-3.5 font-sans text-[10px] font-semibold uppercase tracking-[0.18em] text-[#f3efe8] disabled:cursor-not-allowed disabled:opacity-40">{t.next} <ArrowUpRight size={14} /></button> : <button type="submit" className="group inline-flex items-center gap-3 rounded-full bg-[#211a15] px-5 py-3.5 font-sans text-[10px] font-semibold uppercase tracking-[0.18em] text-[#f3efe8]">{t.send} <ArrowUpRight size={14} /></button>}</div>
        </form>}
      </div>
    </div></section>
    {reviewOpen && <div className="fixed inset-0 z-[90] grid place-items-center bg-[#141210]/75 p-5 backdrop-blur-md"><div className="w-full max-w-[560px] bg-[#f3efe8] p-7 shadow-2xl md:p-10"><div className="flex items-start justify-between gap-4"><div><SectionLabel>WhatsApp / review</SectionLabel><h2 className="mt-5 font-serif text-4xl tracking-[-0.04em]">Review your brief.</h2><p className="mt-3 font-sans text-sm leading-6 text-[#655b52]">Please confirm the details before we open WhatsApp.</p></div><button type="button" onClick={() => setReviewOpen(false)} aria-label="Close"><X size={20} /></button></div><div className="mt-8 space-y-3 border-y border-[#1b1916]/15 py-6 font-sans text-sm">{[[t.company, form.company], [t.country, form.country], [t.leatherType, form.leatherType], [t.thickness, form.thickness], [t.application, form.application || "—"]].map(([label, value]) => <div key={label} className="grid grid-cols-[0.46fr_0.54fr] gap-4"><span className="text-[10px] font-semibold uppercase tracking-[0.15em] text-[#9b795b]">{label}</span><span>{value}</span></div>)}</div><div className="mt-8 flex flex-wrap items-center gap-4"><button type="button" onClick={confirmWhatsApp} className="inline-flex items-center gap-3 rounded-full bg-[#211a15] px-5 py-3.5 font-sans text-[10px] font-semibold uppercase tracking-[0.16em] text-[#f3efe8]">{t.openWhatsApp} <ArrowUpRight size={14} /></button><button type="button" onClick={() => setReviewOpen(false)} className="font-sans text-[10px] font-semibold uppercase tracking-[0.16em] text-[#815d42]">{t.back}</button></div></div></div>}
  </main></PageShell>;
}
