import { ArrowUpRight, Check } from "lucide-react";
import { Link, useLocation } from "wouter";
import { ArrowLink, Breadcrumb, ImageFrame, PageShell, SectionLabel } from "@/components/layout/SiteChrome";
import { collectionCards, heroImageAlt, imagePaths, productStats, serviceAreas } from "@/data/products";
import { useI18n } from "@/i18n";

const markets: Record<string, { title: string; intro: string; detail: string; code: string }> = {
  italy: { title: "Leather supply for Italian makers.", intro: "A direct material conversation for footwear, leather goods and furniture teams across Italy.", detail: "From Istanbul production to European coordination, Anatolia Hides helps Italian product teams move from first brief to dependable material supply.", code: "IT / 01" },
  germany: { title: "Leather supply for German product teams.", intro: "Consistent surfaces, documented process and a practical export desk for Germany.", detail: "Built for teams that value specification, repeatability and clear communication across development and production.", code: "DE / 02" },
  uk: { title: "Turkish leather for the United Kingdom.", intro: "Characterful leather and a measured export route for UK footwear and leather goods makers.", detail: "A considered material partner for teams looking for natural surface, reliable development support and European delivery coordination.", code: "UK / 03" },
};
const sectors: Record<string, { title: string; intro: string; detail: string; code: string }> = {
  footwear: { title: "Leather for considered footwear.", intro: "Surface, flex and finish direction for footwear teams developing the next collection.", detail: "Explore full grain, top grain, suede and split leather directions around the demands of footwear construction.", code: "SECTOR / 01" },
  "leather-goods": { title: "Leather for bags and leather goods.", intro: "Tactile, expressive material direction for products designed to be held and remembered.", detail: "From supple nappa to consistent top grain, we help leather goods teams find the right balance of hand, grain and continuity.", code: "SECTOR / 02" },
  furniture: { title: "Leather for furniture and interiors.", intro: "Reliable surfaces and considered finishes for spaces with a long life.", detail: "A practical route to durable, consistent leather for furniture, hospitality and interior applications.", code: "SECTOR / 03" },
};

export default function Landing() {
  const [location] = useLocation();
  const { t } = useI18n();
  const clean = location.split("?")[0].split("/").filter(Boolean);
  const key = clean[clean.length - 1] || "italy";
  const isSector = clean.includes("sectors");
  const content = (isSector ? sectors[key] : markets[key]) || markets.italy;
  return <PageShell><main><section className="bg-[#e8dfd3] px-5 pb-20 pt-36 md:px-10 md:pb-28 md:pt-48 lg:px-14"><div className="mx-auto max-w-[1440px]"><Breadcrumb current={content.title} /><div className="mt-12 grid gap-12 lg:grid-cols-[1fr_0.72fr] lg:items-end lg:gap-24"><div><SectionLabel number={content.code}>{isSector ? "Sector / Anatolia Hides" : "Market / Anatolia Hides"}</SectionLabel><h1 className="mt-7 max-w-[850px] font-serif text-6xl leading-[0.9] tracking-[-0.06em] md:text-8xl">{content.title}</h1><p className="mt-8 max-w-[620px] font-sans text-base leading-8 text-[#655b52]">{content.intro}</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/contact?enquiry=Request%20a%20sample" className="inline-flex items-center gap-3 rounded-full bg-[#211a15] px-5 py-3.5 font-sans text-[10px] font-semibold uppercase tracking-[0.17em] text-[#f3efe8]">{t.requestSample} <ArrowUpRight size={14} /></Link><Link href="/products" className="inline-flex items-center gap-3 border-b border-[#a48566] pb-2 font-sans text-[10px] font-semibold uppercase tracking-[0.17em] text-[#815d42]">{t.exploreMaterials}</Link></div></div><ImageFrame src={isSector ? imagePaths.products : imagePaths.craft} alt={heroImageAlt} className="aspect-[1.05]" /></div></div></section><section className="bg-[#f3efe8] px-5 py-24 md:px-10 md:py-32 lg:px-14"><div className="mx-auto max-w-[1440px]"><div className="grid gap-12 lg:grid-cols-[0.42fr_1fr] lg:gap-24"><div><SectionLabel number="02">A useful material route</SectionLabel><p className="mt-8 max-w-[230px] font-sans text-xs leading-6 text-[#77695c]">{content.detail}</p></div><div><h2 className="max-w-[780px] font-serif text-5xl leading-[0.95] tracking-[-0.05em] md:text-7xl">What a qualified brief can cover.</h2><div className="mt-12 grid gap-3 md:grid-cols-2">{["Material direction", "Finish and thickness", "Application fit", "Sample coordination", "European delivery", "Repeat programme discussion"].map((item) => <div key={item} className="flex items-center gap-3 border-t border-[#1b1916]/15 py-4 font-sans text-sm text-[#655b52]"><Check size={15} className="text-[#9b795b]" />{item}</div>)}</div><div className="mt-12 flex flex-wrap gap-3">{productStats.map((stat) => <span key={stat.label} className="rounded-full border border-[#1b1916]/15 px-4 py-2.5 font-sans text-[10px] uppercase tracking-[0.16em] text-[#77695c]">{stat.value} / {stat.label}</span>)}</div></div></div></div></section><section className="bg-[#211a15] px-5 py-20 text-[#f3efe8] md:px-10 md:py-28 lg:px-14"><div className="mx-auto flex max-w-[1440px] flex-col justify-between gap-8 md:flex-row md:items-end"><div><SectionLabel light>{isSector ? "Related materials" : "European supply"}</SectionLabel><p className="mt-6 max-w-[640px] font-serif text-4xl leading-[0.98] tracking-[-0.04em] md:text-5xl">The right material changes the conversation before the product is made.</p></div><ArrowLink href="/contact" light>{t.talkExport}</ArrowLink></div></section></main></PageShell>;
}
