import { type MouseEvent, useMemo, useState } from "react";
import { ArrowUpRight, SlidersHorizontal, X } from "lucide-react";
import { Link, useLocation } from "wouter";
import { useI18n } from "@/i18n";
import { ArrowLink, Breadcrumb, ImageFrame, PageShell, SectionLabel } from "@/components/layout/SiteChrome";
import { allApplicationsLabel, allMaterialsLabel, applicationOptions, categoryDescriptions, categoryOptions, imagePaths, libraryIntro, productFilterLabel, products, resultLabel, sectionEyebrows, Product } from "@/data/products";

function ProductCard({ product, index }: { product: Product; index: number }) {
  const [lens, setLens] = useState({ active: false, x: 50, y: 50 });
  const moveLens = (event: MouseEvent<HTMLDivElement>) => { const rect = event.currentTarget.getBoundingClientRect(); setLens({ active: true, x: ((event.clientX - rect.left) / rect.width) * 100, y: ((event.clientY - rect.top) / rect.height) * 100 }); };
  return <Link href={`/products/${product.slug}`} className="group block"><div className="relative aspect-[1.18] overflow-hidden bg-[#ddd3c5]" onMouseMove={moveLens} onMouseLeave={() => setLens((current) => ({ ...current, active: false }))} onMouseEnter={moveLens}><img src={product.image} alt={product.name} loading="lazy" className="h-full w-full object-cover transition duration-700 group-hover:scale-[1.04]" /><div className="absolute inset-0 bg-gradient-to-t from-black/65 via-transparent to-transparent opacity-75" /><div className={`leather-lens pointer-events-none absolute z-10 size-36 rounded-full border border-[#e6c8a7]/90 shadow-[0_12px_35px_rgba(25,15,8,0.38)] ${lens.active ? "opacity-100" : "opacity-0"}`} style={{ left: `calc(${lens.x}% - 4.5rem)`, top: `calc(${lens.y}% - 4.5rem)`, backgroundImage: `url(${product.image})`, backgroundPosition: `${lens.x}% ${lens.y}%` }}><span className="absolute inset-2 rounded-full border border-white/25" /><span className="absolute bottom-4 left-1/2 -translate-x-1/2 whitespace-nowrap rounded-full bg-[#211a15]/75 px-2 py-1 font-sans text-[8px] uppercase tracking-[0.16em] text-[#f3efe8]">surface detail</span></div><div className="absolute inset-x-5 bottom-5 flex items-end justify-between gap-4 text-white"><div><p className="font-sans text-[10px] uppercase tracking-[0.18em] text-[#d4b491]">{product.category} / {product.finish}</p><h2 className="mt-2 font-serif text-3xl tracking-[-0.04em]">{product.name}</h2></div><span className="grid size-9 shrink-0 place-items-center rounded-full border border-white/30 transition duration-300 group-hover:border-[#d4b491] group-hover:bg-[#d4b491] group-hover:text-[#201913]"><ArrowUpRight size={14} /></span></div></div><div className="flex items-start justify-between gap-4 border-b border-[#1b1916]/12 py-4"><p className="max-w-[300px] font-sans text-xs leading-5 text-[#665b51]">{product.description}</p><div className="flex shrink-0 flex-wrap justify-end gap-1.5">{product.tags.slice(0, 2).map((tag) => <span key={tag} className="rounded-full border border-[#1b1916]/12 px-2 py-1 font-sans text-[9px] uppercase tracking-[0.14em] text-[#867565]">{tag}</span>)}</div></div></Link>;
}

export default function Products() {
  const { t } = useI18n();
  const [location] = useLocation();
  const params = new URLSearchParams(location.split("?")[1] || "");
  const initialCategory = params.get("category") && categoryOptions.includes(params.get("category") as (typeof categoryOptions)[number]) ? params.get("category")! : allMaterialsLabel;
  const [category, setCategory] = useState(initialCategory);
  const [application, setApplication] = useState(allApplicationsLabel);
  const [filtersOpen, setFiltersOpen] = useState(false);
  const filtered = useMemo(() => products.filter((product) => (category === allMaterialsLabel || product.category === category) && (application === allApplicationsLabel || product.applications.includes(application))), [category, application]);

  return <PageShell><main><section className="bg-[#e8dfd3] px-5 pb-20 pt-36 md:px-10 md:pb-28 md:pt-48 lg:px-14"><div className="mx-auto max-w-[1440px]"><Breadcrumb current={t.navMaterials} /><div className="mt-12 grid gap-10 lg:grid-cols-[0.42fr_1fr] lg:gap-24"><div><SectionLabel>{t.materialLibrary}</SectionLabel><p className="mt-8 max-w-[230px] font-sans text-xs leading-6 text-[#77695c]">{t.noCart}</p></div><div><h1 className="max-w-[850px] font-serif text-6xl leading-[0.9] tracking-[-0.06em] md:text-8xl">{t.materialTitle.split(" ").slice(0, -1).join(" ")}<br /><em className="font-light text-[#a27655]">{t.materialTitle.split(" ").slice(-1)}</em></h1><p className="mt-8 max-w-[600px] font-sans text-base leading-8 text-[#655b52]">{t.materialIntro}</p></div></div></div></section>
    <section className="bg-[#f3efe8] px-5 py-16 md:px-10 md:py-24 lg:px-14"><div className="mx-auto max-w-[1440px]"><div className="flex flex-col gap-6 border-b border-[#1b1916]/15 pb-6 lg:flex-row lg:items-end lg:justify-between"><div><p className="font-sans text-[10px] font-semibold uppercase tracking-[0.22em] text-[#6e5b49]">{productFilterLabel}</p><p className="mt-3 font-serif text-3xl tracking-[-0.04em]">{filtered.length.toString().padStart(2, "0")} <span className="font-sans text-xs uppercase tracking-[0.18em] text-[#867565]">{resultLabel}</span></p></div><button type="button" onClick={() => setFiltersOpen((value) => !value)} className="inline-flex items-center gap-2 self-start rounded-full border border-[#1b1916]/20 px-4 py-2.5 font-sans text-[10px] font-semibold uppercase tracking-[0.17em] lg:hidden">{filtersOpen ? <X size={14} /> : <SlidersHorizontal size={14} />} {filtersOpen ? "Close" : "Filters"}</button><div className={`${filtersOpen ? "flex" : "hidden"} flex-col gap-5 sm:flex-row lg:flex lg:items-end`}><label className="flex flex-col gap-2 font-sans text-[10px] font-semibold uppercase tracking-[0.16em] text-[#786858]">Surface<select value={category} onChange={(event) => setCategory(event.target.value)} className="min-w-[170px] rounded-none border-b border-[#1b1916]/25 bg-transparent py-2 font-sans text-sm font-normal normal-case tracking-normal text-[#1b1916] outline-none"><option value={allMaterialsLabel}>{allMaterialsLabel}</option>{categoryOptions.slice(1).map((option) => <option key={option} value={option}>{option}</option>)}</select></label><label className="flex flex-col gap-2 font-sans text-[10px] font-semibold uppercase tracking-[0.16em] text-[#786858]">Application<select value={application} onChange={(event) => setApplication(event.target.value)} className="min-w-[180px] rounded-none border-b border-[#1b1916]/25 bg-transparent py-2 font-sans text-sm font-normal normal-case tracking-normal text-[#1b1916] outline-none"><option value={allApplicationsLabel}>{allApplicationsLabel}</option>{applicationOptions.slice(1).map((option) => <option key={option} value={option}>{option}</option>)}</select></label><button type="button" onClick={() => { setCategory(allMaterialsLabel); setApplication(allApplicationsLabel); }} className="pb-2 font-sans text-[10px] uppercase tracking-[0.16em] text-[#9a795c] hover:text-[#1b1916]">Clear</button></div></div><div className="mt-12 grid gap-x-6 gap-y-14 md:grid-cols-2 lg:grid-cols-3">{filtered.map((product, index) => <ProductCard key={product.id} product={product} index={index} />)}</div>{filtered.length === 0 && <div className="border border-dashed border-[#1b1916]/20 px-6 py-20 text-center"><p className="font-serif text-3xl">No materials match that combination yet.</p><p className="mt-3 font-sans text-sm text-[#77695c]">Try widening your brief.</p></div>}</div></section>
    <section className="bg-[#211a15] px-5 py-20 text-[#f3efe8] md:px-10 md:py-28 lg:px-14"><div className="mx-auto flex max-w-[1440px] flex-col justify-between gap-8 md:flex-row md:items-end"><div><SectionLabel light>Material note</SectionLabel><p className="mt-6 max-w-[560px] font-serif text-4xl leading-[0.98] tracking-[-0.04em] md:text-5xl">{t.materialNote}</p></div><ArrowLink href="/contact" light>{t.technical}</ArrowLink></div></section>
  </main></PageShell>;
}

// Catalogue copy and product objects live in data/products.ts so a CMS migration remains straightforward.
