import { ArrowLeft, ArrowUpRight, Check, Ruler, Sparkles } from "lucide-react";
import { Link, useRoute } from "wouter";
import { ArrowLink, Breadcrumb, ImageFrame, PageShell, SectionLabel } from "@/components/layout/SiteChrome";
import { applicationLabel, colourLabel, finishLabel, findProduct, imagePaths, relatedMaterialsLabel, returnToLibraryLabel, selectedMaterialLabel, technicalDetailsLabel, thicknessLabel, products, productContactHref } from "@/data/products";

export default function ProductDetail() {
  const [, baseParams] = useRoute("/products/:slug");
  const [, localizedParams] = useRoute("/:lang/products/:slug");
  const slug = baseParams?.slug || localizedParams?.slug;
  const product = slug ? findProduct(slug) : undefined;
  if (!product) return <PageShell><main className="px-5 pb-32 pt-48 md:px-10 lg:px-14"><div className="mx-auto max-w-[1440px]"><h1 className="font-serif text-6xl tracking-[-0.06em]">Material not found.</h1><Link href="/products" className="mt-8 inline-flex border-b border-[#a48566] pb-2 font-sans text-[10px] font-semibold uppercase tracking-[0.17em]">{returnToLibraryLabel}</Link></div></main></PageShell>;
  const related = products.filter((item) => item.id !== product.id && item.category === product.category).slice(0, 2);
  return <PageShell><main><section className="bg-[#e8dfd3] px-5 pb-16 pt-36 md:px-10 md:pb-24 md:pt-48 lg:px-14"><div className="mx-auto max-w-[1440px]"><Breadcrumb current={product.name} /><div className="mt-12 grid gap-12 lg:grid-cols-[0.9fr_1.1fr] lg:items-end lg:gap-24"><div><SectionLabel>{selectedMaterialLabel}</SectionLabel><h1 className="mt-7 max-w-[720px] font-serif text-6xl leading-[0.9] tracking-[-0.06em] md:text-8xl">{product.name}</h1><p className="mt-6 max-w-[480px] font-sans text-base leading-8 text-[#655b52]">{product.description}</p><div className="mt-8 flex flex-wrap gap-2">{product.tags.map((tag) => <span key={tag} className="rounded-full border border-[#1b1916]/15 px-3 py-2 font-sans text-[10px] uppercase tracking-[0.17em] text-[#77695c]">{tag}</span>)}</div></div><div className="flex items-end justify-end"><Link href="/products" className="group inline-flex items-center gap-2 font-sans text-[10px] font-semibold uppercase tracking-[0.18em] text-[#77695c] transition-colors hover:text-[#1b1916]"><ArrowLeft size={14} className="transition-transform group-hover:-translate-x-1" /> {returnToLibraryLabel}</Link></div></div></div></section>
    <section className="bg-[#f3efe8] px-5 py-16 md:px-10 md:py-24 lg:px-14"><div className="mx-auto max-w-[1440px]"><div className="grid gap-12 lg:grid-cols-[1.15fr_0.85fr] lg:gap-24"><div className="relative"><ImageFrame src={product.image || imagePaths.products} alt={product.name} className="aspect-[1.18]" /><span className="absolute bottom-5 left-5 font-sans text-[10px] uppercase tracking-[0.2em] text-white/72">{product.category} / {product.finish}</span></div><div><p className="font-sans text-[10px] font-semibold uppercase tracking-[0.22em] text-[#9b795b]">{technicalDetailsLabel}</p><div className="mt-8 border-t border-[#1b1916]/15">{[{ label: finishLabel, value: product.finish }, { label: thicknessLabel, value: product.thickness }, { label: applicationLabel, value: product.applications.join(" · ") }, { label: colourLabel, value: product.colors.join(" · ") }].map((item) => <div key={item.label} className="grid grid-cols-[0.35fr_0.65fr] gap-4 border-b border-[#1b1916]/15 py-5"><span className="font-sans text-[10px] font-semibold uppercase tracking-[0.17em] text-[#907963]">{item.label}</span><span className="font-serif text-xl leading-6 tracking-[-0.02em]">{item.value}</span></div>)}</div><div className="mt-10 bg-[#211a15] p-7 text-[#f3efe8]"><div className="flex items-start gap-4"><Sparkles size={17} className="mt-1 shrink-0 text-[#d4b491]" strokeWidth={1.5} /><div><h2 className="font-serif text-2xl">Develop this material</h2><p className="mt-3 font-sans text-sm leading-6 text-white/55">Share your application and target direction with our export desk. We will come back with the appropriate sample route.</p><Link href={productContactHref} className="mt-6 inline-flex items-center gap-3 border-b border-[#d4b491] pb-2 font-sans text-[10px] font-semibold uppercase tracking-[0.18em] text-[#d4b491]">Request technical information <ArrowUpRight size={14} /></Link></div></div></div></div></div></div></section>
    <section className="bg-[#e8dfd3] px-5 py-20 md:px-10 md:py-28 lg:px-14"><div className="mx-auto max-w-[1440px]"><div className="flex items-end justify-between gap-6"><div><SectionLabel>{relatedMaterialsLabel}</SectionLabel><h2 className="mt-5 font-serif text-4xl tracking-[-0.04em]">Within the same direction.</h2></div><ArrowLink href="/products">View all materials</ArrowLink></div><div className="mt-10 grid gap-5 md:grid-cols-2">{related.map((item) => <Link key={item.id} href={`/products/${item.slug}`} className="group flex gap-5 border-t border-[#1b1916]/15 pt-5"><div className="aspect-[1.2] w-40 shrink-0 overflow-hidden md:w-56"><img src={item.image} alt={item.name} className="h-full w-full object-cover transition duration-700 group-hover:scale-[1.04]" /></div><div><p className="font-sans text-[10px] uppercase tracking-[0.18em] text-[#9b795b]">{item.category}</p><h3 className="mt-2 font-serif text-3xl tracking-[-0.03em]">{item.name}</h3><p className="mt-3 font-sans text-xs leading-5 text-[#77695c]">{item.description}</p><span className="mt-5 inline-flex items-center gap-2 font-sans text-[10px] font-semibold uppercase tracking-[0.16em]">Explore <ArrowUpRight size={13} /></span></div></Link>)}</div></div></section>
  </main></PageShell>;
}

// Product detail intentionally ends in an enquiry CTA, never a purchase action.
