import { ArrowUpRight, Check, CircleDashed } from "lucide-react";
import { Link } from "wouter";
import { ArrowLink, Breadcrumb, ImageFrame, NumberedRule, PageShell, SectionLabel } from "@/components/layout/SiteChrome";
import { certifications, craftImageAlt, imagePaths, marketFacts, sectionEyebrows, sustainabilityIntro, sustainabilityPillars, sustainabilityQuote, sustainabilitySignature, warehouseCopy } from "@/data/products";

export default function Sustainability() {
  return <PageShell><main><section className="bg-[#e8dfd3] px-5 pb-20 pt-36 md:px-10 md:pb-28 md:pt-48 lg:px-14"><div className="mx-auto max-w-[1440px]"><Breadcrumb current="Sustainability" /><div className="mt-12 grid gap-10 lg:grid-cols-[0.42fr_1fr] lg:gap-24"><div><SectionLabel number="01">{sectionEyebrows.sustainability}</SectionLabel><p className="mt-8 max-w-[230px] font-sans text-xs leading-6 text-[#77695c]">{warehouseCopy}</p></div><div><h1 className="max-w-[900px] font-serif text-6xl leading-[0.88] tracking-[-0.065em] md:text-8xl">Responsible<br /><em className="font-light text-[#a27655]">by process.</em></h1><p className="mt-8 max-w-[640px] font-sans text-base leading-8 text-[#655b52]">{sustainabilityIntro}</p></div></div></div></section>
    <section id="approach" className="bg-[#f3efe8] px-5 py-24 md:px-10 md:py-32 lg:px-14"><div className="mx-auto max-w-[1440px]"><div className="grid gap-14 lg:grid-cols-[0.85fr_1.15fr] lg:items-center lg:gap-24"><ImageFrame src={imagePaths.craft} alt={craftImageAlt} className="aspect-[1.05]" /><div><p className="max-w-[640px] font-serif text-5xl leading-[0.95] tracking-[-0.05em] md:text-7xl">{sustainabilityQuote}</p><p className="mt-7 font-sans text-[10px] uppercase tracking-[0.2em] text-[#9b795b]">{sustainabilitySignature}</p><div className="mt-14">{sustainabilityPillars.map((item) => <NumberedRule key={item.number} {...item} />)}</div></div></div></div></section>
    <section className="bg-[#211a15] px-5 py-24 text-[#f3efe8] md:px-10 md:py-32 lg:px-14"><div className="mx-auto max-w-[1440px]"><div className="grid gap-14 lg:grid-cols-[0.42fr_1fr] lg:gap-24"><div><SectionLabel light number="02">Evidence, not theatre</SectionLabel><p className="mt-8 max-w-[230px] font-sans text-xs leading-6 text-white/48">Certification status and compliance documents are shared with qualified buyers on request.</p></div><div><h2 className="max-w-[760px] font-serif text-5xl leading-[0.94] tracking-[-0.05em] md:text-7xl">The details behind the<br /><em className="font-light text-[#d4b491]">material story.</em></h2><div className="mt-14 grid gap-4 md:grid-cols-3">{certifications.map((item) => <div key={item.label} className="border-t border-white/20 pt-5"><div className="flex items-center gap-3"><Check size={15} className="text-[#d4b491]" strokeWidth={1.5} /><h3 className="font-serif text-2xl tracking-[-0.03em]">{item.label}</h3></div><p className="mt-4 font-sans text-sm leading-6 text-white/52">{item.detail}</p></div>)}</div><div className="mt-16 flex flex-wrap gap-3">{["Water management", "Chemical discipline", "Waste reduction", "Traceable sourcing"].map((item) => <span key={item} className="inline-flex items-center gap-2 rounded-full border border-white/15 px-4 py-2.5 font-sans text-[10px] uppercase tracking-[0.16em] text-white/65"><CircleDashed size={13} className="text-[#b99b79]" />{item}</span>)}</div></div></div></div></section>
    <section className="bg-[#f3efe8] px-5 py-24 md:px-10 md:py-32 lg:px-14"><div className="mx-auto max-w-[1440px]"><div className="grid gap-12 lg:grid-cols-[1fr_0.58fr] lg:items-end"><div><SectionLabel number="03">Open conversation</SectionLabel><h2 className="mt-7 max-w-[770px] font-serif text-5xl leading-[0.94] tracking-[-0.05em] md:text-7xl">Bring your due diligence<br /><em className="font-light text-[#a27655]">to the table.</em></h2><p className="mt-7 max-w-[560px] font-sans text-base leading-8 text-[#655b52]">We are happy to share the relevant documentation during a qualified material enquiry. Honest detail is part of the service.</p></div><ArrowLink href="/contact?enquiry=Technical%20information">Request documentation</ArrowLink></div></div></section>
  </main></PageShell>;
}
